CC = gcc
CFLAGS = -Wall -Wextra -std=c99
TARGETS = task1 task2 task3 task4 task5 task6 task7 task8 task9 task10 task11

all: $(TARGETS)

task1: task1.c
	$(CC) $(CFLAGS) -o $@ $<

task2: task2.c
	$(CC) $(CFLAGS) -o $@ $<

task3: task3.c
	$(CC) $(CFLAGS) -o $@ $<

task4: task4.c
	$(CC) $(CFLAGS) -o $@ $<

task5: task5.c
	$(CC) $(CFLAGS) -o $@ $<

task6: task6.c
	$(CC) $(CFLAGS) -o $@ $<

task7: task7.c
	$(CC) $(CFLAGS) -o $@ $<

task8: task8.c
	$(CC) $(CFLAGS) -o $@ $<

task9: task9.c
	$(CC) $(CFLAGS) -o $@ $<

task10: task10.c
	$(CC) $(CFLAGS) -o $@ $<

task11: task11.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm -f $(TARGETS)
