CC = gcc
CFLAGS = -Wall -Wextra -std=c99
TARGETS = task1 task2 task3 task4 task5 task6 task7 task8

all: $(TARGETS)

task1: task1.c
	$(CC) $(CFLAGS) -o task1 task1.c

task2: task2.c
	$(CC) $(CFLAGS) -o task2 task2.c

task3: task3.c
	$(CC) $(CFLAGS) -o task3 task3.c

task4: task4.c
	$(CC) $(CFLAGS) -o task4 task4.c

task5: task5.c
	$(CC) $(CFLAGS) -o task5 task5.c

task6: task6.c
	$(CC) $(CFLAGS) -o task6 task6.c

task7: task7.c
	$(CC) $(CFLAGS) -o task7 task7.c

task8: task8.c
	$(CC) $(CFLAGS) -o task8 task8.c

clean:
	rm -f $(TARGETS)

.PHONY: all clean
